@startuml buscaminas

class Juego
{
    + void Juego(int Tam, int minas, int celdas)
    + void manejarEventos(RenderWindow &window, int Tam, int celdas)
    + void run(int Tam, int minas, int celdas)
    - int contarMinasCerca(int x, int y)
    - void colocarBandera(int x, int y)
    - void revelarCelda(int x, int y)

}
class Campo
{
    + bool ganar
    + bool perder
    + int minast 
    + int puntaje
    + Font fuente
    + vector<vector<Celda>> tablero
    + bool ventana
    + void Campo(int Tam, int minas, int celdas)
    - void incializarTablero(int Tam,int celdas)
    - void colocarMinas
}
class Dificultad
{
    + void Dificultad(int Tam, int minas, int celdas)
    + bool seleccion
}

class Celda
{
    + RenctangleShape rect
    + Texto texto
    + bool tieneMina
    + bool revelado
    + int minasCerca
}

Juego "1" *-- "*" Celda
Campo "1" *-- "*" Celda
Campo "1" --o "1" Juego
Juego "1" *-- "1" Dificultad
Campo "1" *-- "1" Dificultad
@enduml